In [ ]:
#import numpy library
import numpy as np

In [ ]:
#create an array using numpy 1D
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('x:',x)
print('\ny:',y)

x: [1 2 3 4]

y: [5 6 7 8]


In [ ]:
#2D array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[8,9,7],[3,2,6]])

print('a:',a)
print('\nb:',b)

a: [[1 2 3]
 [4 5 6]]

b: [[8 9 7]
 [3 2 6]]


In [ ]:
a.shape

(2, 3)

In [ ]:
# creating a matrix of zeros
a = np.zeros(4)
b = np.zeros((4,4))
c = np.zeros((4,4,4))

print('a:',a)
print('\nb:',b)
print('\nc:',c)

a: [0. 0. 0. 0.]

b: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

c: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# creating a matrix of ones
a = np.ones(4)
b = np.ones((4,4))
c = np.ones((4,4,4))

print('a:',a)
print('\nb:',b)
print('\nc:',c)

a: [1. 1. 1. 1.]

b: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#creating identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#creating a diagnol matrix
np.diag([23,4,12,7])

array([[23,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0,  7]])

In [ ]:
# random arrays
import random
np.random.random((3,4))

array([[0.12258229, 0.42460081, 0.32831265, 0.54785049],
       [0.87175077, 0.02866867, 0.86016972, 0.84051287],
       [0.89222152, 0.06911714, 0.22949574, 0.16465876]])

In [ ]:
np.random.randint(1,10,size=(3,3))

array([[9, 6, 9],
       [6, 9, 4],
       [1, 3, 9]])

In [ ]:
# linespace array
np.linspace(1,10,5) # it returns the range of numbers in the given interval and 5 is used to represent that no of integers to be returned.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#arange function
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#reshape function
x = np.arange(20)

In [ ]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# create an array with specific number
np.full((4,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [41]:
#create an array of repeating sequence
np.tile([11,22,33],5)


array([11, 22, 33, 11, 22, 33, 11, 22, 33, 11, 22, 33, 11, 22, 33])

**Array Indexing**

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[8,9,7],[3,2,6]])

print('a:',a)
print('\nb:',b)

a: [[1 2 3]
 [4 5 6]]

b: [[8 9 7]
 [3 2 6]]


In [47]:
print(a[1])
print(a[:1])

[4 5 6]
[[1 2 3]]


In [48]:
print(b[0][1])

9


**Array Slicing**

In [49]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [50]:
print(x[:5])

[1 2 3 4 5]


In [51]:
print(x[2:7])

[3 4 5 6 7]


In [55]:
print(x[::2])

[1 3 5 7 9]


In [57]:
x = np.arange(20)
x = x.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
print(a[1:5,:4])

[[4 5 6]]


**Adding two arrays**

In [73]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[8,9,7],[3,2,6]])

print('a:',a)
print('\nb:',b)

a: [[1 2 3]
 [4 5 6]]

b: [[8 9 7]
 [3 2 6]]


In [65]:
sum = np.concatenate((a,b),axis=1)
sum

array([[1, 2, 3, 8, 9, 7],
       [4, 5, 6, 3, 2, 6]])

In [66]:
sum = np.concatenate((a,b),axis=0)
sum

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7],
       [3, 2, 6]])

In [67]:
#inner product or dot product of arrays
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('x:',x)
print('\ny:',y)

x: [1 2 3 4]

y: [5 6 7 8]


In [68]:
np.dot(x,y)

70

In [69]:
np.inner(x,y)

70

In [74]:
#dot product of 2D arrays
a = np.array([[1,2],[5,6]])
b = np.array([[8,9],[2,6]])

print('a:',a)
print('\nb:',b)

a: [[1 2]
 [5 6]]

b: [[8 9]
 [2 6]]


In [75]:
np.dot(a,b)

array([[12, 21],
       [52, 81]])

In [76]:
#transpose
np.transpose(a)

array([[1, 5],
       [2, 6]])

In [79]:
# or
b.transpose()

array([[8, 2],
       [9, 6]])

In [80]:
#determinant
a = np.array([[1,2,3],[4,5,6],[10,23,15]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 23, 15]])

In [82]:
np.linalg.det(a) # linalg is package of numpy that has the following functions such as determinant , inverse,rank,etc..

63.00000000000005

In [84]:
#True Inverse of an array
np.linalg.inv(a)

array([[-1.        ,  0.61904762, -0.04761905],
       [-0.        , -0.23809524,  0.0952381 ],
       [ 0.66666667, -0.04761905, -0.04761905]])

In [85]:
#pseudo inverse of an array
np.linalg.pinv(a)

array([[-1.00000000e+00,  6.19047619e-01, -4.76190476e-02],
       [ 8.32967820e-17, -2.38095238e-01,  9.52380952e-02],
       [ 6.66666667e-01, -4.76190476e-02, -4.76190476e-02]])

In [90]:
#flatten an array
print('a:\n',a)
print('\nflatten of a:',a.flatten())

a:
 [[ 1  2  3]
 [ 4  5  6]
 [10 23 15]]

flatten of a: [ 1  2  3  4  5  6 10 23 15]
