In [2]:
#import
import numpy as np

In [3]:
#create numpy arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [74]:
#print array
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [75]:
#array size
print(np.size(a))
print(np.size(b))

4
4


In [12]:
#type of array
type(a)

numpy.ndarray

In [18]:
#datatype of array
a.dtype

dtype('int32')

In [42]:
#multi dimension array
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
#dimension
np.ndim(x)

2

In [45]:
#shape of array
np.shape(x)

(3, 4)

In [78]:
#slicing
print(x[:2])
print("")
print(x[::-1])
print("")
print(x[:,2])

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[ 3  7 11]


In [92]:
#boolean array
ar = np.array([0,1,2,0,4,0])
cond = ar>0
temp = ar[cond]
print(temp)

[1 2 4]


In [79]:
#array with float dtype
c = np.array([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8]])
print(c)
print(c.dtype)


[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]
float64


In [96]:
#tuple 
d = ('a','b','c','d')
print(d)
print("")
#tuple to numpy array
d = np.array(d)
d

('a', 'b', 'c', 'd')



array(['a', 'b', 'c', 'd'], dtype='<U1')

In [83]:
#array with random integers
k = np.random.randint(10,size=(2,2,5))
print(k)
print("")
#Flatten the array 
print('flattened array:',k.flatten())

[[[6 4 4 6 8]
  [1 7 5 6 3]]

 [[8 6 9 3 0]
  [9 0 0 6 1]]]

flattened array: [6 4 4 6 8 1 7 5 6 3 8 6 9 3 0 9 0 0 6 1]


In [71]:
#create array with arange function
arr1 = np.arange(10)
print(arr1)
#reshape the array
arr1.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
#array with linspace
arr2 = np.linspace(0,10,15).round(2)
arr2

array([ 0.  ,  0.71,  1.43,  2.14,  2.86,  3.57,  4.29,  5.  ,  5.71,
        6.43,  7.14,  7.86,  8.57,  9.29, 10.  ])